// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

namespace SpacetimeDB 
{
	public static partial class Reducer 
	{
		public static void AddChunk(uint chunkId)
		{
			StdbNetworkManager.instance.InternalCallReducer(new StdbNetworkManager.Message
			{
				fn = "add_chunk",
				args = new object[] { chunkId },
			});
		}
	}
}
