// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

namespace SpacetimeDB
{
	public partial class CheckboxChunk
	{
		[Newtonsoft.Json.JsonProperty("chunk_id")]
		public uint chunkId;
		[Newtonsoft.Json.JsonProperty("state")]
		public System.Collections.Generic.List<byte> state;
		[Newtonsoft.Json.JsonProperty("version")]
		public ulong version;
		public static TypeDef GetTypeDef()
		{
			return TypeDef.Tuple(new ElementDef[]
			{
				new SpacetimeDB.ElementDef(0, SpacetimeDB.TypeDef.BuiltInType(SpacetimeDB.TypeDef.Def.U32)),
				new SpacetimeDB.ElementDef(1, SpacetimeDB.TypeDef.GetVec(SpacetimeDB.TypeDef.BuiltInType(SpacetimeDB.TypeDef.Def.U8))),
				new SpacetimeDB.ElementDef(2, SpacetimeDB.TypeDef.BuiltInType(SpacetimeDB.TypeDef.Def.U64)),
			});
		}

		public static CheckboxChunk From(TypeValue value)
		{
			var tupleValue = value.GetValue(TypeDef.Def.Tuple) as TypeValue[];
			if (tupleValue == null)
			{
				throw new System.InvalidOperationException($"Invalid value (must be Tuple): {value.TypeDef.Type}");
			}

			var state_vec = new System.Collections.Generic.List<byte>();
			var state_vec_source = tupleValue[1].GetValue(TypeDef.Def.Vec) as System.Collections.Generic.List<SpacetimeDB.TypeValue>;
			foreach(var entry in state_vec_source!)
			{
				state_vec.Add((byte)entry.GetValue(TypeDef.Def.U8));
			}
			return new CheckboxChunk
			{
				chunkId = (uint)tupleValue[0].GetValue(TypeDef.Def.U32),
				state = state_vec,
				version = (ulong)tupleValue[2].GetValue(TypeDef.Def.U64),
			};
		}

		public static System.Collections.Generic.IEnumerable<CheckboxChunk> FilterByChunkId(uint value)
		{
			var typeDef = GetTypeDef();
			foreach(var entry in StdbNetworkManager.clientDB.GetEntries("CheckboxChunk"))
			{
				var tupleArr = entry.GetValue(TypeDef.Def.Tuple) as TypeValue[];
				if (tupleArr == null)
				{
					continue;
				}
				var compareValue = (uint)tupleArr[0].GetValue(TypeDef.Def.U32);
				if (compareValue == value)
				{
					var tuple = TypeValue.GetTuple(typeDef, tupleArr);
					yield return From(tuple);
				}
			}
		}

		public static System.Collections.Generic.IEnumerable<CheckboxChunk> FilterByVersion(ulong value)
		{
			var typeDef = GetTypeDef();
			foreach(var entry in StdbNetworkManager.clientDB.GetEntries("CheckboxChunk"))
			{
				var tupleArr = entry.GetValue(TypeDef.Def.Tuple) as TypeValue[];
				if (tupleArr == null)
				{
					continue;
				}
				var compareValue = (ulong)tupleArr[1].GetValue(TypeDef.Def.U64);
				if (compareValue == value)
				{
					var tuple = TypeValue.GetTuple(typeDef, tupleArr);
					yield return From(tuple);
				}
			}
		}

	}
}
