// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

namespace SpacetimeDB 
{
	public static partial class Reducer 
	{
		public static void UpdateCheckbox(uint chunkId, ushort bitOffset, bool checked)
		{
			StdbNetworkManager.instance.InternalCallReducer(new StdbNetworkManager.Message
			{
				fn = "update_checkbox",
				args = new object[] { chunkId, bitOffset, checked },
			});
		}
	}
}
